Universe = vanilla

Output = job.$(Cluster).$(Process).out
Error = job.$(Cluster).$(Process).err
Log = job.log

request_memory=16GB
request_disk=16GB
request_cpus=4

stream_output = True
stream_error = True

Executable = /home/zachgillis/test110524/ggHH-kappa3-kappa4/run.sh
Arguments = -- $(k3) $(k4) $(energy) $(current_directory) $(run_arg)

Queue k3, k4, energy, current_directory, run_arg from alt_instances.txt
